- name: Issue SSL certificate
  uses: Menci/acme@beta-v2
jobs:
  issue-ssl-certificate:
    name: Issue SSL certificate
    runs-on: ubuntu-latest
    steps:
      - uses: Menci/acme@beta-v1
        with:
          version: 3.0.0
          account-conf-content: ${{ secrets.ACME_SH_ACCOUNT_CONF }}
          domains: schneckedde.website
          domains-file: 'ssl.crt'
          append-wildcard: true
          arguments: --dns dns_cf --challenge-alias example.com
          arguments-file: ''
          output-fullchain: output/fullchain.pem
          output-key: output/key.pem
          output-pfx: output/certificate.pfx
          output-pfx-password: qwq
